routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('SuratKeluar', 'SuratKeluarController');
Route::resource('SuratMasuk', 'SuratMasukController');
Route::resource('SuratKeputusan', 'SKController');
Route::resource('Anggota', 'AnggotaController');
Route::resource('Pengurus', 'PengurusController');
Route::resource('Dokumentasi', 'DokumentasiController');
Route::resource('Perpustakaan', 'PerpustakaanController');
Route::resource('Jadwal', 'JadwalController');
Route::resource('Info', 'InfoController');
Route::resource('Usermanagemen', 'UsermanagemenController');
Route::resource('Pesan', 'pesanController');

/*eksport ke excel*/

Route::get('exportsuratkeluar', 'SuratKeluarController@export_excel')->name('exportsuratkeluar');

resources/views/admin/Pengurus.blade.php
@include('layouts.header')
<title>Admin | Pengurus</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Pengurus</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>
<!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
          <div class="card-body">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
            <a href="/Pengurus/create" type="button" class="btn btn-secondary">Tambah</a>
            <!-- <button class="btn btn-dark">Tambah</button> -->
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Nama </th>
                    <th>Tahun LK1</th>
                    <th>Periode</th>
                    <th>Jabatan</th>
                     <th>Gambar</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>No</th>
                    <th>Nama </th>
                    <th>Tahun LK1</th>
                    <th>Periode</th>
                    <th>Jabatan</th>
                     <th>Gambar</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
                <tbody>
                  @foreach($pengurus as $input)
                  <tr>
                    <td>{{$input->id}}</td>
                    <td>{{$input->nama}}</td>
                    <td>{{$input->tahun_lk}}</td>
                    <td>{{$input->periode}}</td>
                    <td>{{$input->jabatan}}</td>
                    <td><img src="{{ URL::to('/') }}/images/{{ $input->image }}" class="img-thumbnail" width="75" /></td>
                    <td>
                      <a href="{{ route('Pengurus.edit',$input->id)}}" class="btn btn-primary">Edit</a>
                      <form action="{{ route('Pengurus.destroy', $input->id)}}" method="post">
                        @csrf
                          @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
@include('layouts.footer')

resources/views/admin/Perpustakaan.blade.php
@include('layouts.header')
<title>Admin | Perpustakaan</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Perpustakaan">Perpustakaan</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>
<!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Data Perpustakaan</div>
          <div class="card-body">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
            <a href="/Perpustakaan/create" type="button" class="btn btn-secondary">Tambah</a>
            <!-- <button class="btn btn-dark">Tambah</button> -->
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Judul </th>
                    <th>Penulis</th>
                    <th>Penerbit</th>
                    <th>Kategori</th>
                     <th>Jumlah</th>
                    <th>Kode</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>No</th>
                    <th>Judul </th>
                    <th>Penulis</th>
                    <th>Penerbit</th>
                    <th>Kategori</th>
                     <th>Jumlah</th>
                    <th>Kode</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
                <tbody>
                  @foreach($perpus as $input)
                  <tr>
                    <td>{{$input->id}}</td>
                    <td>{{$input->judul}}</td>
                    <td>{{$input->penulis}}</td>
                    <td>{{$input->penerbit}}</td>
                    <td>{{$input->kategori}}</td>
                    <td>{{$input->jumlah}}</td>
                    <td>{{$input->kode}}</td>
                    <td>
                      <a href="{{ route('Perpustakaan.edit',$input->id)}}" class="btn btn-primary">Edit</a>
                      <form action="{{ route('Perpustakaan.destroy', $input->id)}}" method="post">
                        @csrf
                          @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
@include('layouts.footer')

resources/views/admin/Pesan.blade.php
@include('layouts.header')
<title>Admin | Pesan</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Pesan">Pesan</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>
<!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
          <div class="card-body">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
            <a href="/Pesan/create" type="button" class="btn btn-secondary">Tambah</a>
            <!-- <button class="btn btn-dark">Tambah</button> -->
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <tbody>
                  @foreach($pesan as $input)
                  <tr>
                    <td>{{$input->nama}}</td>
                    <td>{{$input->email}}</td>
                    <td>{{$input->telepon}}</td>
                    <td>{{$input->pesan}}</td>
                    <td>
                      <a href="{{ route('Pesan.edit',$input->id)}}" class="btn btn-primary">Edit</a>
                      <form action="{{ route('Pesan.destroy', $input->id)}}" method="post">
                        @csrf
                          @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
@include('layouts.footer')

resources/views/admin/SK.blade.php
@include('layouts.header')
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/SuratKeputusan">Surat Keputusan</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>
<!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
          <div class="card-body">
            @if(session()->get('success'))
              <div class="alert alert-success">
                {{ session()->get('success') }}  
              </div><br />
            @endif
            <a href="/SuratKeputusan/create" type="button" class="btn btn-secondary">Tambah</a>
            <!-- <button class="btn btn-dark">Tambah</button> -->
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Nomor Keputusan</th>
                    <th>Tanggal Masehi</th>
                    <th>Tanggal Hijriah</th>
                    <th>Tentang</th>
                    <th>File</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>No</th>
                    <th>Nomor Keputusan</th>
                    <th>Tanggal Masehi</th>
                    <th>Tanggal Hijriah</th>
                    <th>Tentang</th>
                    <th>File</th>
                    <th>Action</th>

                  </tr>
                </tfoot>
                <tbody>
                  @foreach($keputusan as $input)
                  <tr>
                    <td>{{$input->id}}</td>
                    <td>{{$input->nomor_sk}}</td>
                    <td>{{$input->tgl_masehi}}</td>
                    <td>{{$input->tgl_hijriah}}</td>
                    <td>{{$input->tentang}}</td>
                    <td>{{$input->file}}</td>
                    <td>
                      <a href="{{ route('SuratKeputusan.edit',$input->id)}}" class="btn btn-primary">Edit</a>
                      <form action="{{ route('SuratKeputusan.destroy', $input->id)}}" method="post">
                        @csrf
                          @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <!-- <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div> -->
        </div>

@include('layouts.footer')

resources/views/admin/create_Anggota.blade.php
@include('layouts.header')
<title>Tambah Data Anggota</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Anggota">Anggota</a>
          </li>
          <li class="breadcrumb-item active">Tambah Data</li>
        </ol>
<form method="post" action="{{ route('Anggota.store') }}">
    @csrf
          
          <div class="form-group">
              <label for="nama">Nama Anggota</label>
              <input type="text" class="form-control" name="nama"/>
          </div>
          <div class="form-group">
              <label for="tempat_lahir">Tempat Lahir</label>
              <input type="text" class="form-control" name="tempat_lahir"/>
          </div>
          <div class="form-group">
              <label for="tgl_lahir">Tanggal Lahir </label>
              <input type="date" class="form-control" name="tgl_lahir"/>
          </div>
          <div class="form-group">
              <label for="komisariat">Komisariat</label>
              <input type="text" class="form-control" name="komisariat"/>
          </div>
          <div class="form-group">
              <label for="tahun">Tahun LK 1</label>
              <input type="text" class="form-control" name="tahun"/>
          </div>
          <div class="form-group">
              <label for="sk_bpl">No SK BPL</label>
              <input type="text" class="form-control" name="sk_bpl"/>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
@include('layouts.footer')

resources/views/admin/create_Dokumentasi.blade.php
@include('layouts.header')
<title>Buat Dokumentasi</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Dokumentasi">Dokumentasi</a>
          </li>
          <li class="breadcrumb-item active">Tambah Data</li>
        </ol>
<form method="post" action="{{ route('Dokumentasi.store') }}">
    @csrf
          
          <div class="form-group">
              <label for="foto">Foto</label>
              <input type="file" class="form-control" name="foto"/>
          </div>
          <div class="form-group">
              <label for="caption">Caption</label>
              <input type="text" class="form-control" name="caption"/>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
@include('layouts.footer')

resources/views/admin/create_SK.blade.php
@include('layouts.header')
<title>Admin | Create Surat Keputusan</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/SuratKeputusan">Surat Keputusan</a>
          </li>
          <li class="breadcrumb-item active">Tambah Data</li>
        </ol>
<form method="post" action="{{ route('SuratKeputusan.store') }}">
    @csrf
          
          <div class="form-group">
              <label for="nomor_sk">Nomor Surat Keputusan</label>
              <input type="text" class="form-control" name="nomor_sk"/>
          </div>
          <div class="form-group">
              <label for="tentang">Tentang / Perihal </label>
              <input type="text" class="form-control" name="tentang"/>
          </div>
          <div class="form-group">
              <label for="tgl_masehi">Tanggal Masehi </label>
              <input type="date" class="form-control" name="tgl_masehi"/>
          </div>
          <div class="form-group">
              <label for="tgl_hijriah">Tanggal Hijriah</label>
              <input type="text" class="form-control" name="tgl_hijriah"/>
          </div>
          <div class="form-group">
              <label for="file">File Pdf / Scan Gambar</label>
              <input type="file" class="form-control" name="file"/>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
@include('layouts.footer')

resources/views/admin/create_Suratmasuk.blade.php
@include('layouts.header')
<title>Tambah Surat Masuk</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/SuratMasuk">Surat Masuk</a>
          </li>
          <li class="breadcrumb-item active">Tambah Data</li>
        </ol>
<form method="post" action="{{ route('SuratMasuk.store') }}">
    @csrf
          <div class="form-group">
              
              <label for="Kode_arsip">Kode Arsip :</label>
              <input type="text" class="form-control" name="Kode_arsip"/>
          </div>
          <div class="form-group">
              <label for="no_surat">Nomor Surat</label>
              <input type="text" class="form-control" name="no_surat"/>
          </div>
          <div class="form-group">
              <label for="nama_pengirim">Nama Pengirim </label>
              <input type="text" class="form-control" name="nama_pengirim"/>
          </div>
          <div class="form-group">
              <label for="tgl_masehi">Tanggal Masehi </label>
              <input type="date" class="form-control" name="tgl_masehi"/>
          </div>
          <div class="form-group">
              <label for="tgl_hijriah">Tanggal Hijriah</label>
              <input type="text" class="form-control" name="tgl_hijriah"/>
          </div>
          <div class="form-group">
              <label for="perihal">Perihal</label>
              <input type="text" class="form-control" name="perihal"/>
          </div>
          <div class="form-group">
              <label for="file">Scan Surat</label>
              <input type="file" class="form-control" name="file"/>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
      </form>
@include('layouts.footer')

resources/views/admin/dashboard.blade.php
@include('layouts.header')
 <title> Admin - Dashboard</title>
 @include('layouts.navbar')
 <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/home">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>

        <!-- Icon Cards-->
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">26 New Messages!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">11 New Tasks!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">123 New Orders!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-life-ring"></i>
                </div>
                <div class="mr-5">13 New Tickets!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
@include('layouts.footer')

resources/views/admin/edit_Anggota.blade.php
@include('layouts.header')
<title>Ubah Data Anggota</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Anggota">Data Anggota</a>
          </li>
          <li class="breadcrumb-item active">Editor</li>
        </ol>
<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
<form method="post" action="{{ route('Anggota.update', $anggota->id) }}">
    @csrf
    @method('PATCH')
          <div class="form-group">
              <label for="nama">Nama Anggota</label>
              <input type="text" class="form-control" name="nama" value="{{$anggota->nama}}" />
          </div>
          <div class="form-group">
              <label for="tempat_lahir">Tempat Lahir</label>
              <input type="text" class="form-control" name="tempat_lahir" value="{{$anggota->tempat_lahir}}" />
          </div>
          <div class="form-group">
              <label for="tgl_lahir">Tanggal Lahir </label>
              <input type="date" class="form-control" name="tgl_lahir" value="{{$anggota->tgl_lahir}}" />
          </div>
          <div class="form-group">
              <label for="komisariat">Komisariat</label>
              <input type="text" class="form-control" name="komisariat" value="{{$anggota->komisariat}}" />
          </div>
          <div class="form-group">
              <label for="tahun">Tahun LK 1</label>
              <input type="text" class="form-control" name="tahun" value="{{$anggota->tahun}}" />
          </div>
          <div class="form-group">
              <label for="sk_bpl">No SK BPL</label>
              <input type="text" class="form-control" name="sk_bpl" value="{{$anggota->sk_bpl}}" />
          </div>
          <button type="submit" class="btn btn-primary">Update Data</button>
      </form>
@include('layouts.footer')

resources/views/admin/edit_Dokumentasi.blade.php
@include('layouts.header')
<title>Edit Dokumentasi</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Dokumentasi">Dokumentasi</a>
          </li>
          <li class="breadcrumb-item active">Editor</li>
        </ol>
<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
<form method="post" action="{{ route('Dokumentasi.update', $dokumen->id) }}">
    @csrf
    @method('PATCH')
          <div class="form-group">
              <label for="foto">Foto</label>
              <input type="file" class="form-control" name="foto" value="{{$dokumen->foto}}" />
          </div>
          <div class="form-group">
              <label for="caption">Caption</label>
              <input type="text" class="form-control" name="caption" value="{{$dokumen->caption}}" />
          </div>
          <button type="submit" class="btn btn-primary">Update Data</button>
      </form>

@include('layouts.footer')

resources/views/admin/edit_Jadwal.blade.php
@include('layouts.header')
<title>Ubah Data Agenda</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/Jadwal">Data Agenda</a>
          </li>
          <li class="breadcrumb-item active">Editor</li>
        </ol>
<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
<form method="post" action="{{ route('Jadwal.update', $jadwal->id) }}">
    @csrf
    @method('PATCH')
          <div class="form-group">
              <label for="agenda">Nama Agenda</label>
              <input type="text" class="form-control" name="agenda" value="{{$jadwal->agenda}}" />
          </div>
          <div class="form-group">
              <label for="tanggal">Tanggal Pelaksanan</label>
              <input type="date" class="form-control" name="tanggal" value="{{$jadwal->tanggal}}" />
          </div>
          <div class="form-group">
              <label for="waktu">Waktu Pelaksanan</label>
              <input type="time" class="form-control" name="waktu" value="{{$jadwal->waktu}}"/>
          </div> 
          <div class="form-group">
              <label for="tempat">Tempat / Lokasi Pelaksanan</label>
              <input type="text" class="form-control" name="tempat" value="{{$jadwal->tempat}}"/>
          </div>
          <div class="form-group">
              <label for="tanggungjawab">Bidang PenanggungJawab</label>
              <input type="text" class="form-control" name="tanggungjawab" value="{{$jadwal->tanggungjawab}}"/>
          </div>
          <button type="submit" class="btn btn-primary">Update Data</button>
      </form>
@include('layouts.footer')

resources/views/admin/edit_SK.blade.php
@include('layouts.header')
<title>Admin | Edit Surat Keputusan</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/SuratKeputusan">Surat Keputusan</a>
          </li>
          <li class="breadcrumb-item active">Editor</li>
        </ol>
<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
<form method="post" action="{{ route('SuratKeputusan.update', $keputusan->id) }}">
    @csrf
    @method('PATCH')
          <div class="form-group">
              <label for="nomor_sk">Nomor Surat Keputusan</label>
              <input type="text" class="form-control" name="nomor_surat" value="{{$keputusan->nomor_sk}}" />
          </div>
          <div class="form-group">
              <label for="tentang">Tentang / Perihal </label>
              <input type="text" class="form-control" name="tujuan" value="{{$keputusan->tentang}}"/>
          </div>
          <div class="form-group">
              <label for="tgl_masehi">Tanggal Masehi </label>
              <input type="date" class="form-control" name="tgl_masehi" value="{{$keputusan->tgl_masehi}}"/>
          </div>
          <div class="form-group">
              <label for="tgl_hijriah">Tanggal Hijriah</label>
              <input type="text" class="form-control" name="tgl_hijriah" value="{{$keputusan->tgl_hijriah}}"/>
          </div>
          <button type="submit" class="btn btn-primary">Update Data</button>
      </form>
@include('layouts.footer')

resources/views/admin/edit_Suratmasuk.blade.php
@include('layouts.header')
<title>Edit Surat Masuk</title>
@include('layouts.navbar')
<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Surat Masuk</a>
          </li>
          <li class="breadcrumb-item active">Editor</li>
        </ol>
<div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
<form method="post" action="{{ route('SuratMasuk.update', $masuk->id) }}">
    @csrf
    @method('PATCH')
          <div class="form-group">
              <label for="Kode_arsip">Kode Arsip :</label>
              <input type="text" class="form-control" name="Kode_arsip" value="{{$masuk->Kode_arsip}}" />
          </div>
          <div class="form-group">
              <label for="no_surat">Nomor Surat</label>
              <input type="text" class="form-control" name="no_surat" value="{{$masuk->no_surat}}" />
          </div>
          <div class="form-group">
              <label for="nama_pengirim">Nama Pengirim </label>
              <input type="text" class="form-control" name="nama_pengirim" value="{{$masuk->nama_pengirim}}" />
          </div>
          <div class="form-group">
              <label for="tgl_masehi">Tanggal Masehi </label>
              <input type="date" class="form-control" name="tgl_masehi" value="{{$masuk->tgl_masehi}}" />
          </div>
          <div class="form-group">
              <label for="tgl_hijriah">Tanggal Hijriah</label>
              <input type="text" class="form-control" name="tgl_hijriah" value="{{$masuk->tgl_hijriah}}" />
          </div>
          <div class="form-group">
              <label for="perihal">Perihal</label>
              <input type="text" class="form-control" name="perihal" value="{{$masuk->perihal}}" />
          </div>
          <button type="submit" class="btn btn-primary">Update Data</button>
      </form>
@include('layouts.footer')